//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HRM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allow_Leave
    {
        public int A_id { get; set; }
        public Nullable<int> E_leave { get; set; }
        public Nullable<int> S_leave { get; set; }
        public Nullable<int> C_leave { get; set; }
    }
}
