//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HRM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_posts
    {
        public int id { get; set; }
        public string job_title { get; set; }
        public string job_experience { get; set; }
        public string job_qualification { get; set; }
        public Nullable<int> number_of_vacancies { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string job_location { get; set; }
        public string salary_range { get; set; }
        public string job_type { get; set; }
        public string job_description { get; set; }
    }
}
